"""add forum credentials table

Revision ID: 0ffde9f96c48
Revises: a4a60f9c68da
Create Date: 2026-05-17 02:54:16.383854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffde9f96c48'
down_revision: Union[str, None] = 'a4a60f9c68da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create forum_credentials table
    op.create_table(
        'forum_credentials',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('forum_id', sa.String(100), nullable=False, unique=True),
        sa.Column('forum_name', sa.String(200), nullable=False),
        sa.Column('forum_url', sa.String(500), nullable=False),
        sa.Column('username', sa.String(200), nullable=True),
        sa.Column('encrypted_password', sa.Text(), nullable=True),
        sa.Column('login_url', sa.String(500), nullable=True),
        sa.Column('login_form_data', sa.JSON(), nullable=True),
        sa.Column('forum_software', sa.String(50), nullable=True),
        sa.Column('search_url_pattern', sa.String(500), nullable=True),
        sa.Column('result_selector', sa.String(200), nullable=True),
        sa.Column('session_cookies', sa.JSON(), nullable=True),
        sa.Column('auto_login', sa.Boolean(), nullable=True, default=True),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('login_attempts', sa.Integer(), nullable=True, default=0),
        sa.Column('last_login_attempt', sa.DateTime(), nullable=True),
        sa.Column('last_successful_login', sa.DateTime(), nullable=True),
        sa.Column('session_valid_until', sa.DateTime(), nullable=True),
        sa.Column('last_used', sa.DateTime(), nullable=True),
        sa.Column('added_by', sa.String(100), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )
    op.create_index('idx_forum_cred_forum_id', 'forum_credentials', ['forum_id'])
    op.create_index('idx_forum_cred_active', 'forum_credentials', ['is_active'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alert_assignments_id'), 'alert_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_areas_of_interest_id'), 'areas_of_interest', ['id'], unique=False)
    op.create_index(op.f('ix_asset_alerts_id'), 'asset_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_asset_scans_id'), 'asset_scans', ['id'], unique=False)
    op.create_index(op.f('ix_asset_vulnerabilities_id'), 'asset_vulnerabilities', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_breach_results_id'), 'breach_results', ['id'], unique=False)
    op.create_index(op.f('ix_dark_web_mentions_id'), 'dark_web_mentions', ['id'], unique=False)
    op.create_index(op.f('ix_feed_items_id'), 'feed_items', ['id'], unique=False)
    op.create_index(op.f('ix_feed_items_ioc_value'), 'feed_items', ['ioc_value'], unique=False)
    op.create_index(op.f('ix_geo_alerts_id'), 'geo_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_geo_items_id'), 'geo_items', ['id'], unique=False)
    op.create_index(op.f('ix_ioc_tags_id'), 'ioc_tags', ['id'], unique=False)
    op.create_index(op.f('ix_iocs_id'), 'iocs', ['id'], unique=False)
    op.drop_constraint('monitored_assets_value_key', 'monitored_assets', type_='unique')
    op.create_index(op.f('ix_monitored_assets_id'), 'monitored_assets', ['id'], unique=False)
    op.create_index(op.f('ix_monitored_assets_value'), 'monitored_assets', ['value'], unique=True)
    op.create_index(op.f('ix_news_alerts_id'), 'news_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_source_id'), 'news_articles', ['source_id'], unique=False)
    op.create_index(op.f('ix_news_keywords_id'), 'news_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_news_sources_id'), 'news_sources', ['id'], unique=False)
    op.create_index(op.f('ix_notification_configs_id'), 'notification_configs', ['id'], unique=False)
    op.create_index(op.f('ix_paste_hits_id'), 'paste_hits', ['id'], unique=False)
    op.create_index(op.f('ix_profile_attributes_id'), 'profile_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_profile_links_id'), 'profile_links', ['id'], unique=False)
    op.create_index(op.f('ix_profile_notes_id'), 'profile_notes', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_social_accounts_id'), 'social_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_social_alerts_id'), 'social_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_social_keywords_id'), 'social_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_social_posts_id'), 'social_posts', ['id'], unique=False)
    op.create_index(op.f('ix_social_posts_keyword_matched'), 'social_posts', ['keyword_matched'], unique=False)
    op.create_index(op.f('ix_social_posts_platform_post_id'), 'social_posts', ['platform_post_id'], unique=False)
    op.create_index(op.f('ix_threat_feeds_id'), 'threat_feeds', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint('watchlist_keywords_keyword_key', 'watchlist_keywords', type_='unique')
    op.create_index(op.f('ix_watchlist_keywords_id'), 'watchlist_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_keywords_keyword'), 'watchlist_keywords', ['keyword'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('idx_forum_cred_active', table_name='forum_credentials')
    op.drop_index('idx_forum_cred_forum_id', table_name='forum_credentials')
    op.drop_table('forum_credentials')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_keywords_keyword'), table_name='watchlist_keywords')
    op.drop_index(op.f('ix_watchlist_keywords_id'), table_name='watchlist_keywords')
    op.create_unique_constraint('watchlist_keywords_keyword_key', 'watchlist_keywords', ['keyword'])
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_threat_feeds_id'), table_name='threat_feeds')
    op.drop_index(op.f('ix_social_posts_platform_post_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_keyword_matched'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_keywords_id'), table_name='social_keywords')
    op.drop_index(op.f('ix_social_alerts_id'), table_name='social_alerts')
    op.drop_index(op.f('ix_social_accounts_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profile_notes_id'), table_name='profile_notes')
    op.drop_index(op.f('ix_profile_links_id'), table_name='profile_links')
    op.drop_index(op.f('ix_profile_attributes_id'), table_name='profile_attributes')
    op.drop_index(op.f('ix_paste_hits_id'), table_name='paste_hits')
    op.drop_index(op.f('ix_notification_configs_id'), table_name='notification_configs')
    op.drop_index(op.f('ix_news_sources_id'), table_name='news_sources')
    op.drop_index(op.f('ix_news_keywords_id'), table_name='news_keywords')
    op.drop_index(op.f('ix_news_articles_source_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_alerts_id'), table_name='news_alerts')
    op.drop_index(op.f('ix_monitored_assets_value'), table_name='monitored_assets')
    op.drop_index(op.f('ix_monitored_assets_id'), table_name='monitored_assets')
    op.create_unique_constraint('monitored_assets_value_key', 'monitored_assets', ['value'])
    op.drop_index(op.f('ix_iocs_id'), table_name='iocs')
    op.drop_index(op.f('ix_ioc_tags_id'), table_name='ioc_tags')
    op.drop_index(op.f('ix_geo_items_id'), table_name='geo_items')
    op.drop_index(op.f('ix_geo_alerts_id'), table_name='geo_alerts')
    op.drop_index(op.f('ix_feed_items_ioc_value'), table_name='feed_items')
    op.drop_index(op.f('ix_feed_items_id'), table_name='feed_items')
    op.drop_index(op.f('ix_dark_web_mentions_id'), table_name='dark_web_mentions')
    op.drop_index(op.f('ix_breach_results_id'), table_name='breach_results')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_asset_vulnerabilities_id'), table_name='asset_vulnerabilities')
    op.drop_index(op.f('ix_asset_scans_id'), table_name='asset_scans')
    op.drop_index(op.f('ix_asset_alerts_id'), table_name='asset_alerts')
    op.drop_index(op.f('ix_areas_of_interest_id'), table_name='areas_of_interest')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alert_assignments_id'), table_name='alert_assignments')
    # ### end Alembic commands ###
